source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'active_model_serializers', '0.9.3'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

group :production do
  gem 'pg'
end